-- Habilita extensão para cálculo de distâncias (Geolocalização)
CREATE EXTENSION IF NOT EXISTS cube;
CREATE EXTENSION IF NOT EXISTS earthdistance;

-- Tabela de Doadores Voluntários
CREATE TABLE doadores (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  tipo_sanguineo VARCHAR(3) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(2) NOT NULL,
  whatsapp VARCHAR(20) NOT NULL,
  latitude NUMERIC(10, 8),
  longitude NUMERIC(11, 8),
  disponivel BOOLEAN DEFAULT TRUE,
  ultima_doacao DATE
);

-- Tabela de Pedidos Emergenciais
CREATE TABLE pedidos_emergencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL,
  paciente_nome VARCHAR(100) NOT NULL,
  hospital VARCHAR(150) NOT NULL,
  tipo_sanguineo VARCHAR(3) NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(2) NOT NULL,
  whatsapp VARCHAR(20) NOT NULL,
  status VARCHAR(20) DEFAULT 'ativo' -- 'ativo', 'concluido'
);

-- Tabela de Hemocentros Parceiros
CREATE TABLE hemocentros (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  endereco TEXT NOT NULL,
  cidade VARCHAR(100) NOT NULL,
  estado VARCHAR(2) NOT NULL,
  telefone VARCHAR(20) NOT NULL,
  latitude NUMERIC(10, 8) NOT NULL,
  longitude NUMERIC(11, 8) NOT NULL
);

-- Inserção de dados iniciais de Hemocentros
INSERT INTO hemocentros (nome, endereco, cidade, estado, telefone, latitude, longitude) VALUES
('Hemepar Curitiba', 'Travessa João Prosdócimo, 145', 'Curitiba', 'PR', '(41) 3281-4000', -25.4284, -49.2558),
('Fundação Pró-Sangue SP', 'Av. Dr. Enéas Carvalho de Aguiar, 155', 'São Paulo', 'SP', '(11) 4573-7800', -23.5578, -46.6692),
('HemoRio', 'Rua Frei Caneca, 8', 'Rio de Janeiro', 'RJ', '0800 282 0708', -22.9098, -43.1884);